name: CI

on:
  push:
    branches:
      [ main ] 
  pull_request:
    branches:
      [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make libgtest-dev libgmock-dev

    - name: Build Project
      run: make
    
    - name: Build Counter
      run: make counter

  run:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: run single thread
      run: |
        ./bmp sample.bmp --rotate-right --rotate-left --apply-filter
        ./bmp sample1.bmp --rotate-right --rotate-left --apply-filter
        ./bmp sample2.bmp --rotate-right --rotate-left --apply-filter

    - name: run multi thread
      run: |
        ./bmp sample.bmp --rotate-right --rotate-left --apply-filter --threads
        ./bmp sample1.bmp --rotate-right --rotate-left --apply-filter --threads
        ./bmp sample2.bmp --rotate-right --rotate-left --apply-filter --threads

  run counter:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: check counter
      run: |
        ./count sample.bmp
